### PR TITLE
Added clone of Byjus

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This PR fixes the issue UI of Byjus #377. Please review it sir/mam.

### CODE REVIEW

**Review by AyushSingh22 — APPROVED** [review]

**Comment by AyushSingh22** [comment]
Wonderfull @eswarbhageerath

**Comment by eswarbhageerath** [comment]
Thank you sir.

**Comment by eswarbhageerath** [comment]
@AyushSingh22 Please merge PR sir

**Comment by AyushSingh22** [comment]
Wait for our PA @Jaideep25-tech 

> @AyushSingh22 Please merge PR sir

**Review by Jaideep25-tech — APPROVED** [review]

**Pull request merged**
