### PR TITLE
feat: added Music Player

### PR DESCRIPTION
**Pull request by suyogkokaje**

### CODE REVIEW

**Comment by suyogkokaje** [comment]
Please have a look.

**Review by Abirpal202049 — APPROVED** [review]
@suyogkokaje  Very Nice, specially the way you have written the code  with comments make the code more readable is great.😊

**Comment by suyogkokaje** [comment]
> @suyogkokaje Very Nice, specially the way you have written the code with comments make the code more readable is great.😊

Thank you @Abirpal202049 . I wrote comments so that when someone need to use this component with some modification he should be able to understand what's happening in each part of the code. Because JS is bit complex to understand without comments.

**Review by saikatmu31 — APPROVED** [review]

**Comment by saikatmu31** [comment]
The Use of Variables in CSS is Very good Really a Very Professional Code.

**Comment by suyogkokaje** [comment]
> The Use of Variables in CSS is Very good Really a Very Professional Code.

Thank you so much 😅.

**Pull request merged**
