### PR TITLE
Fix: Added code for 'Broken Mirror Text Animation' (Issue #40).

### PR DESCRIPTION
**Pull request by kashyap1905**
Related Issue: #40 

### Preview:

Text_Animation

### CODE REVIEW

**Comment by kashyap1905** [comment]
@nandini7637 Please Review this PR.

**Review by nandini7637 — APPROVED** [review]

**Review by Abirpal202049 — APPROVED** [review]

**Comment by Abirpal202049** [comment]
Nice Animation

**Comment by kashyap1905** [comment]
> Nice Animation

Thank You Sir !

**Review by thepranaygupta — APPROVED** [review]
LGTM 👍

**Comment by kashyap1905** [comment]
> LGTM 👍

Thank You Sir !

**Review by saikatmu31 — APPROVED** [review]

**Pull request merged**
