### PR TITLE
Snake Game

### PR DESCRIPTION
**Pull request by Atif0604**
Fix : #102 
Please review

### CODE REVIEW

**Comment by Atif0604** [comment]
@Abirpal202049 @bhavesh-chaudhari @thepranaygupta @saikatmu31

**Review by nandini7637 — CHANGES_REQUESTED** [review]
1-Add class to body, canva etc html tags on which you have directly applied css
2-Improve responsiveness

**Comment by Atif0604** [comment]
> 1-Add class to body, canva etc html tags on which you have directly applied css 2-Improve responsiveness

@nandini7637 i havent made this for mobile as it would be difficult to play and control on small screen and
and i would all classes to html classes

**Review by nandini7637 — CHANGES_REQUESTED** [review]
Use class of input tag and not the tag itself in css file

**Comment by Atif0604** [comment]
@nandini7637 Changed

**Comment by Atif0604** [comment]
Hey @nandini7637 @thepranaygupta @Abirpal202049 @bhavesh-chaudhari @saikatmu31 Please Review

**Review by nandini7637 — APPROVED** [review]

**Comment by Atif0604** [comment]
@Abirpal202049 @bhavesh-chaudhari @thepranaygupta @saikatmu31
Please review

**Review by bhavesh-chaudhari — APPROVED** [review]

**Pull request merged**
