### PR TITLE
Quiz app

### PR DESCRIPTION
**Pull request by Sumandeep-Kaur**
Fixes: #94

### CODE REVIEW

**Comment by Sumandeep-Kaur** [comment]
Please review @Abirpal202049 @thepranaygupta @bhavesh-chaudhari @saikatmu31

**Review by nandini7637 — CHANGES_REQUESTED** [review]
Please remove the vscode file

**Comment by Sumandeep-Kaur** [comment]
> Please remove the vscode file

Removed! @nandini7637

**Review by bhavesh-chaudhari — CHANGES_REQUESTED** [review]
There seems to be a bug in progress bar(timeline). It is progressing even after the counter has stopped. Can you confirm this ? If this is happening with you too then please try to fix it.

**Comment by Sumandeep-Kaur** [comment]
> There seems to be a bug in progress bar(timeline). It is progressing even after the counter has stopped. Can you confirm this ? If this is happening with you too then please try to fix it.

I have checked, It's working fine!

**Comment by Sumandeep-Kaur** [comment]
Here you can see, I have checked just now:

https://user-images.githubusercontent.com/77191007/153137716-1693c329-1ebd-4678-9405-589b3e8e9176.mp4

**Comment by bhavesh-chaudhari** [comment]
> > There seems to be a bug in progress bar(timeline). It is progressing even after the counter has stopped. Can you confirm this ? If this is happening with you too then please try to fix it.
> 
> I have checked, It's working fine!

I just rechecked and it is working as expected in chrome but this is how it works in firefox - 

https://user-images.githubusercontent.com/74975876/153198119-e470b355-3cb5-44fb-90f8-97130ad9b4e6.mp4

On firefox it is taking around 17 seconds for the timeline to finish as you can see here(expected time to finish progressing is 10 seconds) -
image
|---|

 Whereas it takes around 11 seconds on chrome -
 
image
|---|

This is because browsers don't give much accuracy in setInterval or setTimeout especially when the delay is very small(like 20ms in this example).  

Checkout this for more insights about the bug and how to go about fixing it -
- [How to create accurate timer in javascript ?](https://stackoverflow.com/questions/29971898/how-to-create-an-accurate-timer-in-javascript)
- [Will setInterval drift ?](https://stackoverflow.com/questions/985670/will-setinterval-drift)
- [using requestAnimationFrame instead of setInterval](http://www.javascriptkit.com/javatutors/requestanimationframe.shtml)

**Comment by Sumandeep-Kaur** [comment]
> 

Oh! I haven't checked for other browsers, will fix it soon!

**Comment by bhavesh-chaudhari** [comment]
> Fixed the timeline, Please review! @bhavesh-chaudhari

The timeline is still showing unexpected behaviour as before on firefox. Can you show a preview that it is working fine ?

**Comment by Sumandeep-Kaur** [comment]
> > Fixed the timeline, Please review! @bhavesh-chaudhari
> 
> The timeline is still showing unexpected behaviour as before on firefox. Can you show a preview that it is working fine ?

It is showing same time results.

Here's it is on Chrome--
Screenshot (26)
<br>
And this is on Firefox--
Screenshot (25)

**Comment by bhavesh-chaudhari** [comment]
> > > Fixed the timeline, Please review! @bhavesh-chaudhari
> > 
> > 
> > The timeline is still showing unexpected behaviour as before on firefox. Can you show a preview that it is working fine ?
> 
> It is showing same time results.
> 
> Here's it is on Chrome-- Screenshot (26) And this is on Firefox-- Screenshot (25)

The Time Spent in above images is actually not the time spent but seems to be number of loops you are using(which is independent of browsers). If you read my older message then you can see both no. of loops and time taken. Also the issue is with setInterval() method as it was explained in the previous message. Its behaviour changes with user browsers, devices, etc. so the animation will look different to different users. For more details please go through the links i had shared earlier it does contain the correct solution too !

**Comment by Sumandeep-Kaur** [comment]
Please review! So that I should include it in my project submission.
 @nandini7637 @bhavesh-chaudhari @thepranaygupta

**Review by nandini7637 — APPROVED** [review]

**Review by Abirpal202049 — APPROVED** [review]

**Review by AyushSingh22 — APPROVED** [review]

**Pull request closed without merging**
