### PR TITLE
Added Weather App

### PR DESCRIPTION
**Pull request by Atif0604**
Fix : #106 
@nandini7637 @bhavesh-chaudhari

### CODE REVIEW

**Comment by Atif0604** [comment]
@bhavesh-chaudhari @nandini7637 
please review

**Review by nandini7637 — CHANGES_REQUESTED** [review]
Add class to body tag.

**Comment by Atif0604** [comment]
> Add class to body tag.

@nandini7637 done

**Review by Abirpal202049 — APPROVED** [review]

**Comment by Atif0604** [comment]
@nandini7637 please merge in asap

**Pull request merged**
